name: Quality check
on: [push]

jobs:
  quality:
    name: Node ${{ matrix.node }} - Build, lint, and test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Set npm registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: Install deps and build (with cache)
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
      - name: Build
        run: yarn build
